### PR TITLE
Fix typo in README-KO.md : need to add a space character

### PR DESCRIPTION
**Pull request by devinan**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.

Before Change: "해야할"
After Change: "해야 할" <--- you need to add a space character

### CODE REVIEW

**Comment by erictleung** [comment]
@devinan thanks for the PR! I'm not familiar with Korean, can you explain briefly the impact of this extra space and why it is important? Thanks!

**Comment by devinan** [comment]
Thanks for your reply! 

The term "해야 할" consists of two verbs. (**verb1** + **verb2**)
**Verb 1**: "해야" has the same meaning as **"should"** in English.
**Verb 2**: "할" has the same meaning as **"will be(is/are)"** in English.
 -  해야 할: verb1(해야) + verb2(할)

**Let's think about it.** 
If two verbs are used without extra spaces, they will be thought of as **new words.**

For example, if "should be" is written by someone as "shouldbe". (grammatical errors)
Those who are familiar with the language may find it only **grammatically incorrect**, but those who are learning Korean may think it is **a new word.** (You will try to find a new word in the dictionary.   😱)

So you need to add a space character.

**Comment by erictleung** [comment]
@devinan thanks for the detailed explanation! This helps me understand where you're coming from, even for a "simple" fix as this spacing. In my novice knowledge of Korean, I never noticed the spacing, I thought it was similar to written Chinese. So I appreciate this insight. I'll go ahead and merge your PR!

**Review by erictleung — APPROVED** [review]
LGTM! 👍 Thanks for taking the time to review our translation! ✨

**Pull request merged**
