### PR TITLE
Added awesome_bot to find broken links in README

### LINKED ISSUE #35: Add awesome_bot to find broken links
The [awesome_bot project](https://github.com/dkhamsing/awesome_bot) aims to automatically validate links so that in the case that in the future, one of the links dies or moves, we'll know about it automatically. 

I've set this up before using TravisCI and it works pretty well. Just a thought.

### LINKED ISSUE #37: Add "Getting into Open Source for the First Time"
Very extensive post by Dean McDonnell on step-by-step process to contributing to projects.

Probably good under the ["Useful articles for new open source contributors"](https://github.com/FreeCodeCamp/how-to-contribute-to-open-source#useful-articles-for-new-open-source-contributors) section.

Article: http://www.nearform.com/nodecrunch/first-time-with-open-source/

### PR DESCRIPTION
**Pull request by mmcewan**
This closes #35

### CODE REVIEW

**Comment by erictleung** [comment]
@mmcewan thanks for the pull request!

@QuincyLarson can you turn on the Travis CI (https://travis-ci.org/) for this repository before you or I merge this? Thanks! Afterwards, someone or myself can then add on the build badge.

**Comment by QuincyLarson** [comment]
@mmcewan @erictleung thanks for your patience. I've added Travis, and went ahead and added ESlint for Markdown and JSON while I was at it. https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/56

It looks like there are now some conflicts in the .travis.yml file. 

I noticed that awesome_bot uses ruby. The good news is Travis already has Ruby installed, so we should be able to remove it from the .travis.yml file: https://stackoverflow.com/questions/31235146/how-to-run-node-js-and-ruby-tests-within-one-project-on-travis-ci

Let me know if you need any help resolving this conflict and getting Travis to pass.

**Comment by erictleung** [comment]
@mmcewan we can put the Travis CI scripts within the `package.json` file. I think the following should work if you edit the `package.json` file.

```json
  "scripts": {
    "test": "awesome_bot --allow-redirect --allow-ssl README.md",
    "pretest": "npm run lint",
    "preinstall": "gem install awesome_bot",
    "lint": "eslint . --ext .json --ext .md"
  },
```

Let us know if you have any questions or suggestions to work on this.

**Comment by QuincyLarson** [comment]
@mmcewan have you had a chance to make any of these changes? If you're busy, no worries - just let us know and we can take over this task.

**Comment by erictleung** [comment]
@mmcewan thanks for working on the changes! It looks like you've brought on some extra changes on your PR. Also, it looks like the current virtual machine Travis CI is using has an older Ruby version for the `awesome_bot`. 

In the `.travis.yml` file, you can replace the `before_install` with the following:

```yml
before_install: rvm install 2.2
```

Here's some code to help out fix things.

```bash
# Add a remote to update your local instance
git remote add upstream https://github.com/freeCodeCamp/how-to-contribute-to-open-source.git

# Move to your master to update that branch first
git checkout master

# Update your master branch
git pull --rebase upstream master

# Move to your branch
git checkout fix-issue#35-add-awesome_bot

# Remove your merge of other commits
git reset --hard HEAD~1

# Update your new branch with the changes made from Quincy
git rebase master

# Make your changes here
...
```

Let me know if you have any issues with that. You can find me on Gitter as well.

**Comment by mmcewan** [comment]
Thank you for the guidance @erictleung. I had a few issues getting the extra changes removed from my PR but I think I have it set now. 

Travis CI build passed this time 👍

**Pull request merged**
