### PR TITLE
 i corrected  a word :)

### PR DESCRIPTION
**Pull request by GAbdulWahab**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.

Closes #XXXXX

### CODE REVIEW

**Comment by erictleung** [comment]
@GAbdulWahab thanks for your PR! I'm not familiar with this language, so can you explain briefly what this change does and how it improved the link description? Thanks!

**Comment by GAbdulWahab** [comment]
@erictleung 
I fixed a letter in the word to make it sound clearer
مفتوح-> open
مقتوح -> It has no meaning
  I think this is a mistake of the keyboard because the two letters are next to each other and are similar to each other

image

**Review by erictleung — APPROVED** [review]
LGTM! 👍

**Comment by erictleung** [comment]
@GAbdulWahab thanks for the clarification and information about this change! I appreciate it. I'll go ahead and merge this PR :+1:

**Pull request merged**
