### PR TITLE
Improve Russian translation

### PR DESCRIPTION
**Pull request by evanca**

### CODE REVIEW

**Comment by erictleung** [comment]
Hi @evanca, thanks for taking time to make these improvements. Can you get someone who speaks Russian to peer review this before we can merge this? Thank you.

**Comment by evanca** [comment]
> Hi @evanca, thanks for taking time to make these improvements. Can you get someone who speaks Russian to peer review this before we can merge this? Thank you.

@bormaley999 Could you please my corrections in https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/335/commits/3b64bc24999bd4eb26e93b3bbc87d5fc1d2ff544?

**Comment by Arrivera** [comment]
This is a good Russian translation, can it get merged? Can I help somehow?

**Comment by evanca** [comment]
> This is a good Russian translation, can it get merged? Can I help somehow?

Hi Natalia,

Thank you, please review and add your improvements if any. I didn't touch the bottom part (after "Прямой поиск на GitHub"), I believe the translation can be improved there!

**Comment by Arrivera** [comment]
Hi @evanca! I've never reviewed on github yet so I have some doubts: can I just add comments to the file from RP or should I be in 'Reviewers' somehow? And for the bottom part: should I add comments to the existing file or it's better to create a separate request to fix that part? Sorry, I'm still quite new here.

**Comment by evanca** [comment]
> Hi @evanca! I've never reviewed on github yet so I have some doubts: can I just add comments to the file from RP or should I be in 'Reviewers' somehow? And for the bottom part: should I add comments to the existing file or it's better to create a separate request to fix that part? Sorry, I'm still quite new here.

@erictleung Could you please advice @Arrivera what is the best way to add corrections? I think she could edit the file and make a new PR with latest additions?

**Comment by erictleung** [comment]
@Arrivera hi there. Thanks for your patience and interest in helping out.

The way you can "review" this is going to this page https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/335/files. You can also access this by clicking on "Files changed" near the top of this page underneath the title for this pull request.

From there, you will be able to make comments on the file. If you have line specific feedback, you can click on the line of code, near the left side of where the code starts, and a plus sign should show up. Click on that and it should bring up a box to comment further.

From your earlier comment, you mention this is good enough translation. Let me know if that is the case. From the "Files changed" tab, you can click on the green "Review changes" button to give your approval or other general comments (see image below).

image

**Pull request merged**
