### PR TITLE
Added a resource 

### PR DESCRIPTION
**Pull request by uday03meh**
I have added link to a GitHub repository under under **Contributing to Open Source in general** section of README which will help absolute beginners kickstart their open source journey.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.

Closes #XXXXX

### CODE REVIEW

**Comment by uday03meh** [comment]
Hi! Can someone help me why this PR has failed checks? I don't see anything wrong here :(

**Review by erictleung — APPROVED** [review]
LGTM! 👍 Thanks for finding this resource and adding this to our list! ✨

**Comment by erictleung** [comment]
@uday03meh no need to worry about the CI failing. Those are because of some links having some issues. I've created issues for others to fix those.

**Comment by uday03meh** [comment]
Alright! So this means if I have some additional resources and I make a PR and it fails, I need not worry right?

**Pull request merged**
