### PR TITLE
New License file copied from CC-BY-SA-4.0

### PR DESCRIPTION
**Pull request by ShadowTwo**
Please let me know if the format is ok, and also if you want the file in a different format.

### CODE REVIEW

**Comment by ShadowTwo** [comment]
Sounds good, let me go look up what Markdown is. I have seen it noted on some other items I have read.

**Comment by ShadowTwo** [comment]
That is cool I updated my fork and it picked it up in the pull request.

Also looking at other license files on other projects, is there more to be done other then the copy & paste job as I have done?

**Comment by atjonathan** [comment]
Tagging @QuincyLarson

**Comment by QuincyLarson** [comment]
@ShadowTwo @atjonathan yes - this looks like the typical CC-SA boilerplate. Thanks!

**Comment by QuincyLarson** [comment]
@ShadowTwo @atjonathan it worked!

**Comment by atjonathan** [comment]
🎉

**Comment by shubheksha** [comment]
Yay, @ShadowTwo! 🎉

**Comment by ShadowTwo** [comment]
Thank you all! It was really nice to work through the process and get the first time jitters out. See you all around!

**Pull request merged**
