### PR TITLE
Fixed a typo in a link 🔗 on 'Contributing to Open Source in general' section of the README.md file.

### PR DESCRIPTION
**Pull request by YuheshPandian**
Changed "Opensoure-4-everyone" by Chryz-hub ----> "Opensource-4-everyone" by Chryz-hub

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.

### CODE REVIEW

**Review by StackOverflowIsBetterThanAnyAI — COMMENTED** [review]
well spotted

**Comment by PushpitSB** [comment]
Good work

**Comment by YuheshPandian** [comment]
Any update on this Contribution?

**Review by erictleung — APPROVED** [review]
LGTM! 👍 Thanks for catching this typo! ✨

**Pull request merged**
