### PR TITLE
Create README-DA.md

### PR DESCRIPTION
**Pull request by archy-coder**
Just started translating the README.md file to danish.
- [x] Started work
- [x] Translated all titles
- [x] Started translating links
- [x] Added link to this README-DA.md in main readme file
- [ ] Finished translating links
- [ ] Fully finished work

By the way, I am a beginner at open-source contributing.

### CODE REVIEW

**Comment by erictleung** [comment]
@AryanMangale thanks for starting this translation! One thing that will help get this merged into our repository is to get someone who knows Danish to review your work as a way of code review.

**Comment by carlosdeque-s** [comment]
I can translate some of them

**Comment by erictleung** [comment]
@carlosdeque-s feel free to review the translations with a pull request review https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#about-pull-request-reviews

**Comment by erictleung** [comment]
Closing as stale. Happy coding!

**Pull request closed without merging**
