### PR TITLE
Create README-HI-IN.md

### PR DESCRIPTION
**Pull request by happysahota**
Trying to create Hindi version of guide.

- [x] Work Started
- [ ] Not Complete

### CODE REVIEW

**Comment by happysahota** [comment]
Just started contributing.... Can someone help why All checks have failed?

**Comment by erictleung** [comment]
> 
> 
> Just started contributing.... Can someone help why All checks have failed?

Links in the main README have failed those checked. They have been addressed in other PRs, so no need to worry about it with your PR.

Thanks for your interest in taking on the Hindi translation!

**Comment by AryanMangale** [comment]
Hello.
I can also understand Hindi, so I can check the Hindi translation.
Good work!

**Comment by happysahota** [comment]
Made this pull request active for merge so that other can collaborate.

**Comment by raisedadead** [comment]
Hi, thanks for making this pull-request. I reviewed it and we would typically want to have a substantial amount of translation for the file.

Also, we would want human translations for the file and not the generic machine translations from Google. I encourage you to update the PR or open it at a later time when you are ready.

**Comment by erictleung** [comment]
@happysahota @AryanMangale the PR https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/462 is more fully translated. Feel free to take your translation efforts over here to review their translation. Thanks!

**Comment by raisedadead** [comment]
Hi @happysahota closing this since we haven't heard from you in a bit. We encourage you to follow Eric's advice above.

**Pull request closed without merging**
