### PR TITLE
chore: update action name, add secrets

### PR DESCRIPTION
**Pull request by raisedadead**
The goal of this PR is:

- [x] Use GitHub Actions instead of Travis CI - we are prefering the former lately.
- [x] Use `danger` in tandem with `awesome_bot` to help ensure the links are working, non-redirecting, etc.
- [x] Remove all the npm tooling which needs constant upkeep.

### CODE REVIEW

**Comment by raisedadead** [comment]
#### Eureka!

**Review by nhcarrigan — APPROVED** [review]
This is neat!

**Comment by nhcarrigan** [comment]
Have we tested it against a duplicate link yet?

**Comment by raisedadead** [comment]
> Have we tested it against a duplicate link yet?

Yes the ones that are marked `Dupe` are duplicates.

**Comment by nhcarrigan** [comment]
Oh wow I totally missed that. 😅

**Comment by raisedadead** [comment]
Merging this in to get the CI going. I accidentally used the camperbot account to create and track an issue to fix the links which are duplicated and are redirecting with a 301

**Pull request merged**
