### PR TITLE
Added Punctuation

### PR DESCRIPTION
**Pull request by nuckarronjones**
All sentences end with a period. Noticed the "Up For Grabs" link under "List of initiatives" section did not have consistent formatting with the rest of the document. I added a period at the end of that sentence. 

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.

Closes #XXXXX

### CODE REVIEW

**Comment by nuckarronjones** [comment]
I do not know why the check had failed.

**Comment by nuckarronjones** [comment]
It says "all checks failed," does anyone have any idea as to why?

**Review by erictleung — APPROVED** [review]
LGTM! :+1: Thanks for catching this error inconsistency.

**Comment by erictleung** [comment]
@nuckarronjones the errors in the CI are because it checks links in all of the README files, which some of them aren't as up to date as the main English README. You can ignore for now.

**Comment by nuckarronjones** [comment]
Thank you for your feedback! Noted for future reference. 

-Nicholas Jones

**Pull request merged**
