### PR TITLE
Add GNOME #13

### PR DESCRIPTION
**Pull request by meetsha**
Fixes Issue #13.
I created a new section "Open Source Projects to contribute to" for this where other links for Docker, React etc can be added.

### CODE REVIEW

**Comment by shubheksha** [comment]
@meetsha, thank you for you PR! Could you please go through the [Contributing guide](https://github.com/FreeCodeCamp/how-to-contribute-to-open-source/blob/master/CONTRIBUTING.md) and update your PR? 
Specifically:
- Add the [organisation] label since Gnome is one.
- Add all the relevant links in the form of a list.

Feel free to ask in case you've questions - thanks for helping out!

**Comment by meetsha** [comment]
- Could you give an example of adding the organisation label?  
 Is it done like Just [GNOME](https://wiki.gnome.org/Newcomers)[organisation]?
- There is just one link for gnome. Do you want me to add the links of other organisations as well, or am I missing something?

**Comment by agarwal-akash** [comment]
@shubheksha could you add one project to the README.md? It would help us to add more projects to it in the desired format 😄

**Comment by pdurbin** [comment]
@agarwal-akash I like your idea of adding a first project to the README so additional projects can be added. I just mentioned this pull request in #44.

**Comment by erictleung** [comment]
@meetsha hi there! Thanks for contributing! So we recently decided to create a separate file for projects and organizations to contribute to, which you can find [here](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/PROJECTS.md). Please rebase your commits and move your changes over to the separate file `PROJECTS.md`. If you have any questions for how to do that, let us know. Thanks!

**Comment by erictleung** [comment]
@meetsha thanks again for the pull request. But I'm going to close this as it seems to have gone stale. Please comment back here if you're still interested in contributing. Apologies again for the late response. Happy coding!

**Pull request closed without merging**
