### PR TITLE
Corrected spelling mistakes and added new content according to english readme file

### PR DESCRIPTION
**Pull request by vighnesh-chavan**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

Corrected spelling mistakes and added new conenet and links from english readme, futher translated this new content into marathi.

### CODE REVIEW

**Comment by vighnesh-chavan** [comment]
Hello, I'm new to contributing in open source, I don't know why the test case failed but I check in the details section mentioning about some issues in some links, as you can see below, but I don't have these links in my file. Please help in this concern.
Screenshot (28)

**Review by erictleung — APPROVED** [review]
LGTM! 👍 Thanks for fixing some spelling mistakes

**Comment by erictleung** [comment]
> 
> 
> Hello, I'm new to contributing in open source, I don't know why the test case failed but I checked in the details section mentioning about some issues in some links, as you can see below, but I don't have these links in my file. Please help in this concern. Screenshot (28)

No worries on these failing for now. These can be address in another pull request. Hpapy coding!

**Comment by vighnesh-chavan** [comment]
Thanks for your reply.

**Pull request merged**
