### PR TITLE
added link and description to README.md section: Open Source books

### PR DESCRIPTION
**Pull request by Neidley**
added link and description to README.md section: Open Source books
screen shot 2018-07-18 at 6 47 20 pm

### CODE REVIEW

**Comment by erictleung** [comment]
@Neidley Thanks for the PR! LGTM, but just curious, any particular reason why this PR changes the list style? Also FYI, you can close and reference issues [with GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by Neidley** [comment]
Closes #145

**Comment by Neidley** [comment]
@erictleung, got those styling changes reversed and made commit message "Closes #145".

Thank you for sharing the article about closing issues with GitHub keywords!

**Comment by Neidley** [comment]
I guess I should wait to close this until it's merged(?) 
not sure what the proper etiquette is on that.

**Pull request merged**
