### PR TITLE
Update README-FA.md

### LINKED ISSUE #475: Persian Translation Errors
Hi, There are some grammatical errors in the Persian/Farsi version of the Readme file which is the result of direct word-to-word translations( like how the google translate works for us) and needs to be fixed for better readability.

### PR DESCRIPTION
**Pull request by Hessam-Emami**
fix #475 
this PR aims to improve the translations of the Farsi version of the README file

### CODE REVIEW

**Comment by erictleung** [comment]
@Hessam-Emami thanks for the pull request! I don't know Persian/Farsi so, I'm unable to properly review this pull request. If possible, please find a friend or other contributor who knows Persian/Farsi who can review this. Thanks!

**Comment by Hessam-Emami** [comment]
@erictleung You are right, I just checked the git history for the commits on the Farsi version of the file and it seems @BaseMax was the one who originally created it.
Dear @BaseMax, If you know Farsi/Persian I totally appreciate it if you take a look at my changes.
However, if Max doesn't know Persian, then I guess our only choice would be to simply trust each other :)
by the way, I'm a native Persian speaker and I also speak French and Italian besides English.

**Comment by BaseMax** [comment]
Hi Eric,

Sorry, I had forgotten. Some time ago, I added Persian language and I am happy that it has been noticed and is gradually improving.
Thanks to Hesam for improving the text.

I reviewed the changes and the changes are helpful and I suggest you please **accept** this.

After merging this, I will make other changes to the file myself.
Looking forward to hearing back from you soon! 

Regards,
Max

**Comment by Hessam-Emami** [comment]
@erictleung 
Dear Eric,
Since @BaseMax reviewed and approved my changes. I would really appreciate it if you accept my PR.

**Review by erictleung — APPROVED** [review]
LGTM! 👍

**Comment by erictleung** [comment]
@Hessam-Emami @BaseMax thanks to you both! ✨

**Pull request merged**
