### PR TITLE
Translating README.md To Malayalam(On-going)

### PR DESCRIPTION
**Pull request by varghesejose2020**
it is in progress

### CODE REVIEW

**Comment by varghesejose2020** [comment]
help wanted

**Comment by Arun-kc** [comment]
Hi @varghesejose2020, should I fork this project from your forked one? I'm pretty new to open-source contributions😅

**Comment by varghesejose2020** [comment]
proceed :+1:  @Arun-kc

**Comment by erictleung** [comment]
@Arun-kc if you're still interested in contributing and reviewing, you can click on the [Files Changed](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/526/files) tab and make comments on your changes to the file. Click around the line numbers where a plus sign will appear and this window should pop-up.

image

From there, there is the left-most button that can be used to make suggestions to the text. Let me know if you have other questions.

**Review by varghesejose2020 — COMMENTED** [review]
@Arun-kc

**Review by varghesejose2020 — COMMENTED** [review]
updated latest

**Review by varghesejose2020 — COMMENTED** [review]
updated allmost please approve these changes @erictleung

**Review by josephjosedev — APPROVED** [review]
approved

**Review by iamrahulrnair — CHANGES_REQUESTED** [review]
You have changed the Don't translate section, please review that

**Review by erictleung — APPROVED** [review]
LGTM! 👍 Thanks for taking the time to help translate this file to Malayalam! ✨

**Pull request merged**
