### PR TITLE
Added templates for projects and orgs to be added

### LINKED ISSUE #5: Add If Me - app to share mental health experiences with loved ones
https://github.com/julianguyen/ifme
Issue label: [newbiefriendly](https://github.com/julianguyen/ifme/issues?q=is%3Aissue+is%3Aopen+label%3Anewbiefriendly)

### PR DESCRIPTION
**Pull request by shubheksha**
Fixes #5 
I made a basic skeleton for folks to get started contributing. I'd really appreciate feedback on how this can be done better.
/cc @QuincyLarson, @erictleung

### CODE REVIEW

**Comment by erictleung** [comment]
@shubheksha I like the idea of highlighting projects and organizations to contribute to, but doesn't this duplicate the effort in http://up-for-grabs.net/#/? Or is the purpose of adding these to have a more curated and smaller set of places to contribute and having a link to their contributing documents as well?

**Comment by shubheksha** [comment]
@erictleung, yes - that's the idea! I want a one-stop resource for beginners with all relevant links/docs in a project or org

**Comment by QuincyLarson** [comment]
@erictleung I'd also like to add that this is an opportunity to create a soft of "cliff notes" for contributing to open source projects - and possibly even standardized dimensions upon which we can index open source projects.

**Comment by erictleung** [comment]
@shubheksha @QuincyLarson ah I see. Make sense with the context of this repository :smile: 

Some comments on this PR

- I anticipate that there be a lot of good projects to contribute to. So I feel that this might clutter the README page a bit. Maybe make a separate file dedicated to a list of these?
- Additionally, if we have a standardized way to representing the components of how to contribute to an open source project, maybe put it into a table? I can see this backfiring if there are different types of "cliff notes" for each project. But just putting that out there.

**Comment by raisedadead** [comment]
@erictleung yes, that is completely correct, I recently put up #36 to discuss this. Have added a few points, hope you have a look when you have moment.

**Comment by erictleung** [comment]
@shubheksha hi there! So we moved the discussion over to https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/36 and made a decision on creating a separate file for projects and organizations. I'll be closing this issue as the initial structure has just now been established with https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/45. Thanks for initiating the creation of the project and organization template! Happy coding!

**Pull request closed without merging**
