### PR TITLE
Create readme-telugu.md

### PR DESCRIPTION
**Pull request by Sanketh149**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by erictleung** [comment]
@Sanketh149 hi there! Sorry for the delayed review. I just took a look at your additions and it looks like you've put in a lot of work so far. 

However, I have two concerns:

1. The formatting is not the same as the original README.md file
2. I'm not qualified to review the translation itself. If you have someone else who can confirm the translation is good, then I'll be happy to merge this PR. 

Until then, I'll leave this open until both of these concerns are resolved. Thanks!

**Comment by Sanketh149** [comment]
Hi sir,
Sorry to ask you but Can i know if there is any better software for
language conversion?

**Comment by erictleung** [comment]
@Sanketh149 you can use software to help translate, but we hope that fluent or native speakers can help translate this more naturally. I hope that makes sense to help with your pull request.

**Comment by hindu-muppala** [comment]
@Sanketh149 ,If you are not working , I can able to work  on this issue.

**Comment by dywa-varaprasad** [comment]
@Sanketh149, @hindu-muppala namastey, Telugu translation completed or can I join ??

**Comment by hindu-muppala** [comment]
@dywa-varaprasad ,I think so no one is working on this issue now. I think so we can work, if we ask the  project maintener to assign.

**Comment by dywa-varaprasad** [comment]
@hindu-muppala yes that could be great! @erictleun please resolve this. we're willing to contribute to translate into Telugu. Kindly guide us. **BTW I'm new to open Source**

**Comment by dywa-varaprasad** [comment]
@erictleung hello, I would like to review or translate into Telugu please let me know further steps

**Comment by erictleung** [comment]
Closing in favor of this PR because it is more comprehensive https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/786. Thanks for your efforts! Please take a look at this and improve as necessary. Happy coding!

**Pull request closed without merging**
