### PR TITLE
Chore/add jenkins

### LINKED ISSUE #19: Add Jenkins
https://wiki.jenkins-ci.org/display/JENKINS/Beginners+Guide+to+Contributing

### PR DESCRIPTION
**Pull request by bismarkhenao**
Closes #19

### CODE REVIEW

**Comment by bismarkhenao** [comment]
@erictleung could you please check this PR? Closes #19

**Comment by erictleung** [comment]
@bismarkhenao see https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/280#issuecomment-463308760

**Review by oneemo95 — COMMENTED** [review]
Duplicate of #284 
Duplicate of #1

**Comment by oneemo95** [comment]
Duplicate of #580

**Pull request closed without merging**
