### PR TITLE
Update: README.md - Add Code Review Anxiety Workbook in opensource bo…

### LINKED ISSUE #992: Add Code Review Anxiety Workbook
## Suggested link

https://developer-success-lab.gitbook.io/code-review-anxiety-workbook-1

## Reasoning
 
New contributors and even seasoned contributor programmers can benefit in reading more about managing anxiety when making pull requests and contributions to repositories.

## Section

Open-source books

### PR DESCRIPTION
**Pull request by Cibiyanna26**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.

Closes #992

**Issue #992** 

Add Code Review Anxiety Workbook

**Whats updated in the PR**
     Added Code Review Anxiety Workbook article in the Open-Source Books section of README.md file.

### CODE REVIEW

**Review by erictleung — APPROVED** [review]
LGTM! 👍 Thanks for taking the time to work through GitHub, make these changes, and make a pull request ✨ And congrats on your first contribution to this repository!!

**Comment by Cibiyanna26** [comment]
@erictleung I really happy to contribute to freeCodeCamp like I feel very proud that I got an opportunity to contribute to this repository.

**Comment by Cibiyanna26** [comment]
if you are ok with it, can we connect on linkedIn?

**Comment by erictleung** [comment]
@Cibiyanna26 sure, feel free to find my LinkedIn on my GitHub profile. And feel free to take a look here for other opportunities to contribute to freeCodeCamp if you so choose https://contribute.freecodecamp.org/intro/

**Comment by Cibiyanna26** [comment]
@erictleung I have given the connection eric and thanks🙌

**Pull request merged**
