### PR TITLE
Updating README-ID.md With New Sources & Fixing Sentences

### PR DESCRIPTION
**Pull request by altela**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Hi,
Pull Request are made to add new link of sources from README.md to make this translation updated. I also fix punctuation, letters, etcetera, in several sentences to make it more readable in Bahasa Indonesia. If you already reviewed and have a comment, or there's something to be fixed please let me know. I'd be glad to help with anything i could. I hope this fixes are helpful for the community.

### CODE REVIEW

**Comment by erictleung** [comment]
@Altela great, thanks! I don't have the expertise to review the translations properly, so I'll leave this open for another person who can review it. Feel free to tag someone who can help review your translations.

**Comment by Altela** [comment]
Hi @YosephKS 
Since you are the original author would you like to verify this update and correction?
Also feel free to give your feedback.

Thanks!

**Comment by YosephKS** [comment]
> Hi @YosephKS
> Since you are the original author would you like to verify this update and correction?
> Also feel free to give your feedback.
> 
> Thanks!

yeah sure thing, I'll have it checked @Altela

**Comment by Altela** [comment]
> > Hi @YosephKS
> > Since you are the original author would you like to verify this update and correction?
> > Also feel free to give your feedback.
> > Thanks!
> 
> yeah sure thing, I'll have it checked @Altela

Thanks! feel free to merge it if you've done reviewing @YosephKS

**Review by YosephKS — APPROVED** [review]
@erictleung looks good! Much better than my original translation! you can have it merged

**Review by YosephKS — APPROVED** [review]

**Comment by Altela** [comment]
Hi @erictleung 
This PR to fix several changes is already checked by the original author and currently hanging on my PR list.
Could you help to merge this PR so it'll be closed?

Thanks!

**Pull request merged**
