### PR TITLE
Update PROJECTS.md

### PR DESCRIPTION
**Pull request by aasim-syed**
I Have highlighted the important topics

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by CodingSpecies** [comment]
@aasim-syed , I think you should use markdown to make code blocks.  This makes the code more cleaner. 
just put 2 backticks ( ` ): `example`.
thank you.

**Review by erictleung — APPROVED** [review]
LGTM! :+1: Thanks for styling the projects for us! ✨

**Review by CodingSpecies — APPROVED** [review]
Thank you @erictleung ! LGTM

**Comment by erictleung** [comment]
@CodingSpecies thanks for the suggestion for adding backticks 😄

**Comment by CodingSpecies** [comment]
@erictleung , is it possible for me to join this organisation, so I can help out more, or is this a professional business sort of organisation?

**Comment by erictleung** [comment]
> @erictleung , is it possible for me to join this organisation, so I can help out more, or is this a professional business sort of organisation?

@CodingSpecies hello and thanks for your interest in helping out! freeCodeCamp is a nonprofit and relies on the support of volunteers. There is a small group of individuals who help in a professional manner. These individuals have shown a commitment to helping out consistently over time. But getting accepted to the GitHub organization is a matter of showing up and triaging issues here or other ways that are listed here and engaging in the community https://contribute.freecodecamp.org/#/. I hope that helps.

**Comment by CodingSpecies** [comment]
@erictleung Thank you! :)

**Review by oneemo95 — COMMENTED** [review]
Duplicate of #580

**Pull request merged**
